'use client';
import * as React from 'react';
import Link from 'next/link';
import { ArrowRight, ChevronDown } from 'lucide-react';
export function HeroiCinematico({ imagem='/heroi.jpg', kicker='Química em movimento', titulo='Entenda a matéria.', tituloItalico='Veja as conexões.', subtitulo='Uma trilha visual para dominar os conceitos que aparecem na prova.', alturaRolagem=220 }: { imagem?:string;kicker?:string;titulo?:string;tituloItalico?:string;subtitulo?:string;alturaRolagem?:number }) {
 const ref=React.useRef<HTMLElement>(null); const [prog,setProg]=React.useState(0);
 React.useEffect(()=>{let raf=0;const medir=()=>{const el=ref.current;if(!el)return;const r=el.getBoundingClientRect(),total=r.height-window.innerHeight,p=total>0?Math.min(1,Math.max(0,-r.top/total)):0;setProg(p);document.documentElement.dataset.heroi=r.bottom>120?'on':'off'};const rolar=()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(medir)};medir();addEventListener('scroll',rolar,{passive:true});addEventListener('resize',rolar);return()=>{removeEventListener('scroll',rolar);removeEventListener('resize',rolar);cancelAnimationFrame(raf);delete document.documentElement.dataset.heroi}},[]);
 const op=Math.max(0,1-prog*1.9);
 return <section ref={ref} aria-label={kicker} className="relative -mt-[var(--alt-cabecalho)]" style={{height:`calc(${alturaRolagem}vh + var(--alt-cabecalho))`}}><div className="sticky top-0 grid h-screen place-items-center overflow-hidden bg-[#070B0C]"><div aria-hidden className="absolute inset-0 overflow-hidden"><div className="absolute inset-0 animate-kenburns bg-cover bg-center will-change-transform" style={{backgroundImage:`url(${imagem})`,transform:`scale(${1+prog*.22}) translateY(${prog*40}px)`,filter:`saturate(.88) contrast(1.05) brightness(${.66-prog*.2})`}}/></div><div aria-hidden className="absolute inset-0"><div className="absolute left-1/2 top-1/2 h-[46rem] w-[46rem] -translate-x-1/2 -translate-y-1/2 rounded-full bg-[rgb(34,200,160)]/10 blur-[120px]"/><div className="absolute -right-24 top-6 h-[30rem] w-[30rem] animate-drift rounded-full bg-[rgb(214,122,47)]/12 blur-[120px]"/></div><div aria-hidden className="absolute inset-0 bg-[linear-gradient(180deg,rgba(7,11,12,.72)_0%,rgba(7,11,12,.34)_34%,rgba(7,11,12,.80)_100%)]"/><div aria-hidden className="grao absolute inset-0 opacity-[.35]"/><div className="relative z-10 mx-auto max-w-4xl px-6 text-center will-change-transform" style={{opacity:op,transform:`translateY(${-prog*90}px)`,filter:`blur(${prog*7}px)`}}><span className="label animate-riseIn text-[rgb(34,200,160)]">{kicker}</span><h1 className="mt-4 font-display text-[clamp(2.6rem,7.5vw,5.6rem)] font-black leading-[.95] tracking-[-.03em] text-white"><span className="block animate-riseIn">{titulo}</span><em className="mt-1 block animate-riseIn text-accent" style={{fontStyle:'italic'}}>{tituloItalico}</em></h1><p className="mx-auto mt-6 max-w-xl text-lg leading-relaxed text-white/80">{subtitulo}</p><div className="mt-9 flex flex-wrap items-center justify-center gap-3"><Link href="/trilha" className="btn btn-primary btn-lg">Começar pela trilha <ArrowRight className="h-4 w-4"/></Link><Link href="/questoes" className="btn btn-lg border-0 bg-white/10 text-white backdrop-blur" style={{boxShadow:'0 5px 0 0 rgba(255,255,255,.14)'}}>Ir direto às questões</Link></div></div><div className="absolute bottom-7 left-1/2 z-10 -translate-x-1/2 text-center" style={{opacity:Math.max(0,1-prog*3.2)}}><span className="label block text-white/55">role para explorar</span><ChevronDown className="mx-auto mt-1 h-4 w-4 animate-bob text-white/55"/></div><div aria-hidden className="absolute inset-x-0 bottom-0 h-[3px] bg-white/10"><div className="h-full bg-[rgb(34,200,160)]" style={{width:`${prog*100}%`}}/></div></div></section>
}
