import Link from 'next/link';
import { BookOpen, ListChecks, Timer, Bot, ArrowRight, Sparkles } from 'lucide-react';
import { HeroiCinematico } from '@/components/heroi/HeroiCinematico';
import { getCurriculo, getQuestoes } from '@/lib/conteudo';
const CORES=['var(--c-eixo-1)','var(--c-eixo-2)','var(--c-eixo-3)','var(--c-eixo-4)','var(--c-eixo-5)'];
export default function Home(){const curriculo=getCurriculo(),questoes=getQuestoes(),totalTemas=curriculo.eixos.reduce((s,e)=>s+e.temas.length,0);const totalQ=questoes.length;return <><HeroiCinematico/>
<section className="mx-auto grid max-w-7xl gap-4 px-4 py-16 sm:grid-cols-2 sm:px-6 lg:grid-cols-4">{[{href:'/trilha',Icone:BookOpen,titulo:'Trilha de conteúdos',texto:'Os 5 eixos na ordem certa de estudo, com o que você já concluiu.'},{href:'/questoes',Icone:ListChecks,titulo:'Banco de questões',texto:'Filtre por tema, ano e dificuldade. Erros viram lista de revisão.'},{href:'/simulado',Icone:Timer,titulo:'Simulado cronometrado',texto:'Monte uma prova do tamanho que quiser e receba o relatório.'},{href:'/assistente',Icone:Bot,titulo:'Assistente de química',texto:'Explica, corrige e puxa exemplos dos materiais do curso.'}].map(({href,Icone,titulo,texto},i)=><Link key={href} href={href} className="card card-hover grao group relative overflow-hidden p-5" style={{'--c-tema':CORES[i]} as React.CSSProperties}><span className="relative grid h-11 w-11 place-items-center rounded-2xl text-white shadow-card" style={{background:'rgb(var(--c-tema))'}}><Icone className="h-5 w-5"/></span><p className="relative mt-3.5 font-display text-lg font-black leading-tight">{titulo}</p><p className="relative mt-1 text-sm leading-snug text-muted">{texto}</p><span className="relative mt-3 inline-flex items-center gap-1 text-sm font-bold text-tema opacity-0 transition-all group-hover:translate-x-1 group-hover:opacity-100">abrir <ArrowRight className="h-3.5 w-3.5"/></span></Link>)}</section>
<section className="relative mx-4 overflow-hidden rounded-4xl bg-[#0A1013] px-6 py-16 sm:mx-6 lg:mx-auto lg:max-w-7xl"><div aria-hidden className="absolute -left-24 -top-32 h-[30rem] w-[30rem] animate-drift rounded-full bg-brandGlow/12 blur-3xl"/><div className="relative mx-auto max-w-2xl text-center"><span className="label text-brandGlow">a ordem importa</span><h2 className="mt-3 text-[clamp(1.8rem,4vw,2.8rem)] font-black leading-tight text-white">{totalTemas} temas, {totalQ} questões — <span className="italic text-accent">na sequência que faz o conteúdo grudar.</span></h2><p className="mx-auto mt-4 max-w-lg text-white/65">Nada de estudar solto. A trilha organiza os temas e cada questão respondida mapeia seus pontos fracos.</p><Link href="/trilha" className="btn btn-primary btn-lg mt-7">Ver minha trilha <ArrowRight className="h-4 w-4"/></Link></div></section>
<section className="mx-auto max-w-7xl px-4 py-16 sm:px-6"><div className="mb-6 flex flex-wrap items-end gap-3"><div><span className="label flex items-center gap-1.5"><Sparkles className="h-3 w-3"/> currículo completo</span><h2 className="mt-1 text-3xl font-black">Os cinco eixos do curso</h2><p className="mt-1 text-muted">Clique em um tema para abrir a teoria, os materiais e as questões.</p></div><Link href="/questoes" className="btn btn-outline btn-sm ml-auto">Ir direto ao banco <ArrowRight className="h-3.5 w-3.5"/></Link></div><div className="grid items-start gap-5 lg:grid-cols-2">{curriculo.eixos.map((eixo,i)=><section key={eixo.id} className="card-tema card-hover relative flex flex-col overflow-hidden" style={{'--c-tema':CORES[i%5]} as React.CSSProperties}><header className="relative p-5 pt-6"><p className="label">Eixo {i+1}</p><h3 className="mt-.5 text-xl font-black leading-tight">{eixo.titulo}</h3><p className="mt-1.5 text-sm leading-snug text-muted">{eixo.descricao}</p></header><ul className="relative flex-1 divide-y divide-line border-y border-line">{eixo.temas.map((t,n)=><li key={t.id}><Link href={`/temas/${t.slug}`} className="group flex items-center gap-3 px-5 py-2.5 transition-colors hover:bg-tema/10"><span className="grid h-6 w-6 shrink-0 place-items-center rounded-md bg-surface2 font-mono text-[10px] font-bold text-muted">{n+1}</span><span className="flex-1 truncate text-sm font-semibold group-hover:text-tema">{t.titulo}</span></Link></li>)}</ul><footer className="relative flex items-center gap-3 px-5 py-3.5"><p className="label">{eixo.temas.length} temas</p><Link href="/trilha" className="btn btn-sm btn-tema ml-auto">Estudar <ArrowRight className="h-3.5 w-3.5"/></Link></footer></section>)}</div></section></>}
